service: denjis-unitTest-app

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-2

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: hello
          method: get
